modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="vanilla_"
version="1.0.0"
displayName="Vanilla +"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="OMEN 870-296nz, MCreator"

[[dependencies.vanilla_]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



